// SPDX-License-Identifier: Apache-2.0
package zap

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const includeBegin = "# ZAP MANAGED DEPENDENCIES BEGIN"
const includeEnd = "# ZAP MANAGED DEPENDENCIES END"
const applyBegin = "# ZAP MANAGED TARGETS BEGIN"
const applyEnd = "# ZAP MANAGED TARGETS END"

func safeName(s string) string {
	re := regexp.MustCompile(`[^A-Za-z0-9_]`)
	return re.ReplaceAllString(s, "_")
}

func GenerateCMake(cfg *Config) (string, error) {
	cfg.normalize()
	if err := validateConfig(cfg, true); err != nil {
		return "", err
	}
	env := strings.ToLower(cfg.Project.Environment)
	var b strings.Builder
	b.WriteString("# Generated by zap from ../zap.yml. DO NOT EDIT BY HAND.\n")
	b.WriteString("# This file is Zap-owned; user CMake belongs in CMakeLists.txt outside ZAP MANAGED blocks.\n")
	b.WriteString("include(FetchContent)\n\n")

	// Verification is on by default. Offline mode skips remote ls-remote checks but
	// still verifies the local checkout's origin, locked commit, and cleanliness.
	b.WriteString("option(ZAP_VERIFY_DEPENDENCIES \"Verify Zap-managed dependencies before configure\" ON)\n")
	b.WriteString("option(ZAP_OFFLINE \"Skip remote dependency checks; still verify local locked checkouts\" OFF)\n")
	b.WriteString("if(DEFINED ENV{ZAP_OFFLINE} AND NOT \"$ENV{ZAP_OFFLINE}\" STREQUAL \"\")\n    set(ZAP_OFFLINE ON CACHE BOOL \"Zap offline mode\" FORCE)\nendif()\n")
	b.WriteString("if(ZAP_VERIFY_DEPENDENCIES)\n")
	b.WriteString("    set(ZAP_EXECUTABLE \"\" CACHE FILEPATH \"Path to the Zap dependency verifier\")\n")
	b.WriteString("    if(NOT ZAP_EXECUTABLE AND DEFINED ENV{ZAP_EXECUTABLE})\n        file(TO_CMAKE_PATH \"$ENV{ZAP_EXECUTABLE}\" _zap_executable_env)\n        set(ZAP_EXECUTABLE \"${_zap_executable_env}\" CACHE FILEPATH \"Path to the Zap dependency verifier\" FORCE)\n    endif()\n")
	b.WriteString("    if(NOT ZAP_EXECUTABLE)\n        find_program(ZAP_EXECUTABLE NAMES zap zap.exe HINTS \"${CMAKE_SOURCE_DIR}\")\n    endif()\n")
	b.WriteString("    if(NOT ZAP_EXECUTABLE)\n")
	b.WriteString("        message(FATAL_ERROR \"Zap dependency verification is enabled but the 'zap' executable was not found. Install Zap, or explicitly configure with -DZAP_VERIFY_DEPENDENCIES=OFF. For offline work keep verification enabled and use -DZAP_OFFLINE=ON.\")\n")
	b.WriteString("    endif()\n")
	b.WriteString("    set(_zap_verify_args verify --cmake)\n")
	b.WriteString("    if(ZAP_OFFLINE)\n        list(APPEND _zap_verify_args --offline)\n    endif()\n")
	b.WriteString("    execute_process(\n        COMMAND \"${ZAP_EXECUTABLE}\" ${_zap_verify_args}\n        WORKING_DIRECTORY \"${CMAKE_SOURCE_DIR}\"\n        RESULT_VARIABLE _zap_verify_result\n        OUTPUT_VARIABLE _zap_verify_out\n        ERROR_VARIABLE _zap_verify_err\n    )\n")
	b.WriteString("    if(NOT _zap_verify_result EQUAL 0)\n        message(FATAL_ERROR \"Zap dependency verification failed:\\n${_zap_verify_out}${_zap_verify_err}\")\n    endif()\n")
	b.WriteString("endif()\n\n")

	fmt.Fprintf(&b, "set(ZAP_DEPS_DIR %s CACHE PATH \"Zap dependency source directory\")\n", cmakeBracket(cfg.Project.DepsDir))
	b.WriteString("if(NOT IS_ABSOLUTE \"${ZAP_DEPS_DIR}\")\n    set(ZAP_DEPS_DIR \"${CMAKE_SOURCE_DIR}/${ZAP_DEPS_DIR}\")\nendif()\n\n")
	var links []string
	for _, name := range cfg.DependencyOrder {
		dep := cfg.Dependencies[name]
		if dep == nil {
			continue
		}
		typ := strings.ToLower(dep.Type)
		safe := safeName(name)
		if env == "zephyr" && dep.ZephyrModule {
			fmt.Fprintf(&b, "# %s is supplied to Zephyr through ZEPHYR_MODULES by zap/west.\n\n", name)
			continue
		}
		override := dep.OverrideVar
		if override != "" {
			fmt.Fprintf(&b, "set(%s \"\" CACHE PATH \"Optional local source override for %s\")\n", override, name)
			fmt.Fprintf(&b, "if(NOT %s AND DEFINED ENV{%s})\n    file(TO_CMAKE_PATH \"$ENV{%s}\" _zap_%s_env)\n    set(%s \"${_zap_%s_env}\" CACHE PATH \"Optional local source override for %s\" FORCE)\nendif()\n", override, override, override, safe, override, safe, name)
		}
		fmt.Fprintf(&b, "set(_zap_%s_local \"\")\n", safe)
		if override != "" {
			fmt.Fprintf(&b, "if(%s)\n    set(_zap_%s_local \"${%s}\")\n", override, safe, override)
			b.WriteString("else()\n")
		}
		prefix := ""
		if override != "" {
			prefix = "    "
		}
		fmt.Fprintf(&b, "%sif(EXISTS \"${ZAP_DEPS_DIR}/%s/CMakeLists.txt\")\n%s    set(_zap_%s_local \"${ZAP_DEPS_DIR}/%s\")\n%sendif()\n", prefix, safe, prefix, safe, safe, prefix)
		if override != "" {
			b.WriteString("endif()\n")
		}
		fmt.Fprintf(&b, "if(_zap_%s_local)\n    FetchContent_Declare(\n        %s\n        SOURCE_DIR \"${_zap_%s_local}\"\n        BINARY_DIR \"${CMAKE_BINARY_DIR}/_zapdeps/%s\"\n    )\nelse()\n", safe, safe, safe, safe)
		switch typ {
		case "git":
			// A commit hash is immutable. CMake explicitly recommends hashes for
			// traceability; GIT_SHALLOW cannot be combined with a commit hash.
			fmt.Fprintf(&b, "    # Requested ref: %s; locked commit: %s\n", dep.Version, dep.Commit)
			fmt.Fprintf(&b, "    FetchContent_Declare(\n        %s\n        GIT_REPOSITORY %s\n        GIT_TAG        %s\n        GIT_PROGRESS   TRUE\n        BINARY_DIR     \"${CMAKE_BINARY_DIR}/_zapdeps/%s\"\n    )\n", safe, cmakeBracket(dep.URI), cmakeBracket(strings.ToLower(dep.Commit)), safe)
		case "url":
			fmt.Fprintf(&b, "    FetchContent_Declare(\n        %s\n        URL            %s\n        URL_HASH       %s\n        BINARY_DIR     \"${CMAKE_BINARY_DIR}/_zapdeps/%s\"\n    )\n", safe, cmakeBracket(dep.URI), cmakeBracket(dep.Hash), safe)
		case "path":
			fmt.Fprintf(&b, "    FetchContent_Declare(\n        %s\n        SOURCE_DIR     %s\n        BINARY_DIR     \"${CMAKE_BINARY_DIR}/_zapdeps/%s\"\n    )\n", safe, cmakeBracket(dep.URI), safe)
		}
		b.WriteString("endif()\n")
		fmt.Fprintf(&b, "FetchContent_MakeAvailable(%s)\n\n", safe)
		for _, c := range dep.Components {
			if c != "" {
				links = append(links, c)
			}
		}
	}
	b.WriteString("function(zap_apply_dependencies target_name)\n    if(NOT TARGET \"${target_name}\")\n        message(FATAL_ERROR \"zap_apply_dependencies: target '${target_name}' does not exist\")\n    endif()\n")
	if len(links) > 0 && env != "zephyr" {
		for _, c := range links {
			fmt.Fprintf(&b, "    set_property(TARGET \"${target_name}\" APPEND PROPERTY LINK_LIBRARIES %s)\n", c)
		}
	} else {
		b.WriteString("    # No direct CMake component links are required for this configuration.\n")
	}
	b.WriteString("endfunction()\n")
	return b.String(), nil
}

func GenerateZephyrConf(cfg *Config) string {
	var b strings.Builder
	b.WriteString("# Generated by zap from ../zap.yml. DO NOT EDIT BY HAND.\n")
	n := 0
	for _, name := range cfg.DependencyOrder {
		if dep := cfg.Dependencies[name]; dep != nil {
			for _, v := range dep.ZephyrConfig {
				if v != "" {
					b.WriteString(v)
					b.WriteByte('\n')
					n++
				}
			}
		}
	}
	if n == 0 {
		b.WriteString("# No Zephyr Kconfig fragments are requested.\n")
	}
	return b.String()
}

func InferEnvironment(cmake string) string {
	if strings.Contains(cmake, "pico_sdk_import") || strings.Contains(cmake, "pico_sdk_init") {
		return "pico-sdk"
	}
	if regexp.MustCompile(`find_package\s*\(\s*Zephyr`).MatchString(cmake) {
		return "zephyr"
	}
	return "generic"
}
func InferTarget(cmake string) string {
	if m := regexp.MustCompile(`(?m)^\s*add_executable\s*\(\s*([A-Za-z0-9_.+\-]+)`).FindStringSubmatch(cmake); m != nil {
		return m[1]
	}
	if m := regexp.MustCompile(`(?m)^\s*project\s*\(\s*([A-Za-z0-9_.+\-]+)`).FindStringSubmatch(cmake); m != nil {
		return m[1]
	}
	return "app"
}
func InferPicoBoard(cmake string) string {
	if m := regexp.MustCompile(`(?m)^\s*set\s*\(\s*PICO_BOARD\s+([A-Za-z0-9_.+\-]+)`).FindStringSubmatch(cmake); m != nil {
		return m[1]
	}
	return "pico2_w"
}

func managedBlock(text, begin, end, body string) (string, bool, error) {
	bc, ec := strings.Count(text, begin), strings.Count(text, end)
	if bc != ec || bc > 1 {
		return text, false, fmt.Errorf("CMake Zap markers are malformed for %q/%q; Zap will not modify the file", begin, end)
	}
	block := begin + "\n" +
		"# Managed by zap. Zap may replace only text between this BEGIN/END pair.\n" +
		"# User CMake outside this block is never rewritten by zap.\n" +
		body + "\n" + end
	if bc == 0 {
		return block, false, nil
	}
	start := strings.Index(text, begin)
	endStart := strings.Index(text[start:], end)
	if endStart < 0 {
		return text, false, fmt.Errorf("CMake Zap marker %q has no matching end marker", begin)
	}
	endPos := start + endStart + len(end)
	return text[:start] + block + text[endPos:], true, nil
}

func validateAllManagedMarkers(text string) error {
	for _, pair := range [][2]string{{includeBegin, includeEnd}, {applyBegin, applyEnd}} {
		bc, ec := strings.Count(text, pair[0]), strings.Count(text, pair[1])
		if bc != ec || bc > 1 {
			return fmt.Errorf("CMake Zap markers are malformed for %q/%q; no edits were made", pair[0], pair[1])
		}
	}
	return nil
}

func EnsureCMakeIntegration(projectRoot string, cfg *Config) error {
	if err := validateConfig(cfg, false); err != nil {
		return err
	}
	path := filepath.Join(projectRoot, "CMakeLists.txt")
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("CMakeLists.txt was not found in the project root")
	}
	original := string(data)
	if err := validateAllManagedMarkers(original); err != nil {
		return err
	}
	text := original

	includeBody := "include(\"${CMAKE_CURRENT_LIST_DIR}/cmake/zap_deps.cmake\")"
	includeBlock, existed, err := managedBlock(text, includeBegin, includeEnd, includeBody)
	if err != nil {
		return err
	}
	if existed {
		text = includeBlock
	} else {
		env := strings.ToLower(cfg.Project.Environment)
		var re *regexp.Regexp
		if env == "pico-sdk" {
			re = regexp.MustCompile(`(?m)^\s*pico_sdk_init\s*\(\s*\)\s*$`)
		} else {
			re = regexp.MustCompile(`(?m)^\s*project\s*\([^\r\n]+\)\s*$`)
		}
		loc := re.FindStringIndex(text)
		if loc == nil {
			return fmt.Errorf("could not find the CMake insertion point for %s; add cmake/zap_deps.cmake manually", env)
		}
		text = text[:loc[1]] + "\n\n" + includeBlock + "\n" + text[loc[1]:]
	}

	target := cfg.Project.Target
	if target == "" {
		target = InferTarget(text)
	}
	applyBody := "if(COMMAND zap_apply_dependencies)\n    zap_apply_dependencies(" + target + ")\nendif()"
	applyBlock, existed, err := managedBlock(text, applyBegin, applyEnd, applyBody)
	if err != nil {
		return err
	}
	if existed {
		text = applyBlock
	} else {
		text = strings.TrimRight(text, " \t\r\n") + "\n\n" + applyBlock + "\n"
	}

	if text != original {
		st, _ := os.Stat(path)
		mode := os.FileMode(0o644)
		if st != nil {
			mode = st.Mode().Perm()
		}
		return os.WriteFile(path, []byte(text), mode)
	}
	return nil
}
