// SPDX-License-Identifier: Apache-2.0
package zap

import (
	"fmt"
	"path/filepath"
	"strings"
)

// A declared SDK is authoritative; installed SDK discovery is only a fallback.
func (p *Project) managedPicoSDK(c *Config, lock *Lockfile) (string, error) {
	if !strings.EqualFold(c.Project.Environment, "pico-sdk") || lock == nil {
		return "", nil
	}
	d := lock.Dependencies["pico-sdk"]
	if d == nil {
		return "", nil
	}
	if d.Type != "git" && d.Type != "path" {
		return "", fmt.Errorf("pico-sdk must use a Git or local path dependency so it is available before CMake project()")
	}
	return filepath.Abs(p.dependencyPathLocked(c, "pico-sdk", d))
}

func (p *Project) generatePicoSDK(c *Config, lock *Lockfile) (string, error) {
	path, err := p.managedPicoSDK(c, lock)
	if err != nil {
		return "", err
	}
	header := "# Generated by Zap. Include before pico_sdk_import.cmake and project().\n"
	if path == "" {
		return header + "# No managed Pico SDK; use the project's installed SDK selection.\n", nil
	}
	return header + fmt.Sprintf(`set(PICO_SDK_PATH %s CACHE PATH "Zap-managed Pico SDK" FORCE)
if(NOT EXISTS "${PICO_SDK_PATH}/pico_sdk_init.cmake")
    message(FATAL_ERROR "Managed Pico SDK is missing; run zap sync --no-configure.")
endif()
`, cmakeBracket(filepath.ToSlash(path))), nil
}
